---
name: radionets
channels:
    - fastai
    - pytorch
    - defaults
    - conda-forge
dependencies:
  - python
  - pytorch
  - cudatoolkit
  - cartopy
  - numpy
  - numba
  - sphinx>=7.0.0
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  - tomli
  - pip
  - pip:
    - towncrier
    - sphinx-automodapi
    - -e .
